spring.application.name=iam-server

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/iam_server}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:iam_dev}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:iam_dev}

app.security.jwt.secret=${JWT_SECRET:dev-only-change-this-secret-dev-only-change-this-secret}
app.security.jwt.access-token-ttl=15m
app.security.refresh-token-ttl=14d

app.oauth2.issuer=${OAUTH2_ISSUER:http://localhost:8080}
app.oauth2.jwk.private-key=${OAUTH2_JWK_PRIVATE_KEY:}
app.oauth2.jwk.public-key=${OAUTH2_JWK_PUBLIC_KEY:}
app.oauth2.jwk.private-key-path=${OAUTH2_JWK_PRIVATE_KEY_PATH:}
app.oauth2.jwk.public-key-path=${OAUTH2_JWK_PUBLIC_KEY_PATH:}
app.oauth2.jwk.key-id=${OAUTH2_JWK_KEY_ID:5c9e2e2a-63e2-4700-b7e0-2f0bda5b68f8}

app.management.cors.allowed-origins=${MANAGEMENT_CORS_ALLOWED_ORIGINS:http://localhost:3000,https://iam-server-fe.vercel.app}

app.bootstrap.admin.enabled=true
app.bootstrap.admin.email=admin@example.com
app.bootstrap.admin.password=admin@123
