spring.application.name=iam-server

spring.datasource.url=jdbc:postgresql://localhost:5432/iam_server
spring.datasource.username=iam_dev
spring.datasource.password=iam_dev

app.security.jwt.secret=${JWT_SECRET:dev-only-change-this-secret-dev-only-change-this-secret}
app.security.jwt.access-token-ttl=15m
app.security.refresh-token-ttl=14d

app.oauth2.issuer=${OAUTH2_ISSUER:http://localhost:8080}
app.oauth2.jwk.private-key=${OAUTH2_JWK_PRIVATE_KEY:}
app.oauth2.jwk.public-key=${OAUTH2_JWK_PUBLIC_KEY:}

app.bootstrap.admin.enabled=true
app.bootstrap.admin.email=admin@example.com
app.bootstrap.admin.password=admin@123
