create table users (
    id uuid primary key,
    email varchar(320) not null unique,
    password_hash varchar(255) not null,
    status varchar(50) not null,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create table roles (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique,
    created_at timestamptz not null
);

create table user_roles (
    user_id uuid not null references users(id) on delete cascade,
    role_id bigint not null references roles(id) on delete restrict,
    assigned_at timestamptz not null,
    primary key (user_id, role_id)
);

create table auth_events (
    id bigint generated by default as identity primary key,
    user_id uuid null references users(id) on delete set null,
    event_type varchar(100) not null,
    subject varchar(320) null,
    user_agent varchar(512) null,
    occurred_at timestamptz not null
);

create index idx_user_roles_user_id on user_roles(user_id);
create index idx_user_roles_role_id on user_roles(role_id);
create index idx_auth_events_user_occurred_at on auth_events(user_id, occurred_at desc);
create index idx_auth_events_event_type_occurred_at on auth_events(event_type, occurred_at desc);
create index idx_auth_events_subject_occurred_at on auth_events(subject, occurred_at desc);
