create table refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id uuid not null references users(id) on delete cascade,
    token_hash varchar(255) not null unique,
    token_family_id uuid not null,
    user_agent varchar(512) null,
    created_at timestamptz not null,
    expires_at timestamptz not null,
    revoked_at timestamptz null,
    replaced_by_token_id bigint null references refresh_tokens(id)
);

create index idx_refresh_tokens_user_id on refresh_tokens(user_id);
create index idx_refresh_tokens_token_family_id on refresh_tokens(token_family_id);
create index idx_refresh_tokens_expires_at on refresh_tokens(expires_at);
