package com.example.iam.account.domain.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

@Entity
@Table(name = "users")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class User {
    /*
     * IDs are generated by the domain factory instead of the database so a new
     * user has an identity before it is persisted. That lets registration create
     * related rows or events in the same workflow without waiting for a flush.
     * User IDs are UUIDs because user records are public-facing identity data
     * that may appear in logs, events, APIs, and integrations; unlike internal
     * lookup data such as roles, they should not be easy to enumerate, meaning if we
     * have a user 100 then the next can be guessed as 101 if we are using DB generated Ids
     */
    @Id
    private UUID id;

    @Column(nullable = false, unique = true, length = 320)
    private String email;

    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 50)
    private AccountStatus status;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    public User(UUID id, String email, String passwordHash, AccountStatus status, Instant createdAt, Instant updatedAt) {
        /*
         * Constructor guards keep the entity from being created in a state that
         * would violate the database schema or authentication rules.
         */
        this.id = Objects.requireNonNull(id, "id must not be null");
        this.email = Objects.requireNonNull(email, "email must not be null");
        this.passwordHash = Objects.requireNonNull(passwordHash, "passwordHash must not be null");
        this.status = Objects.requireNonNull(status, "status must not be null");
        this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
        this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
    }

    /*
     * Builds a new user object for the registration workflow. This does not
     * save the user, check email uniqueness, hash passwords, assign roles, or
     * send messages; those belong to the application service.
     *
     * The timestamp is supplied by the application workflow instead of calling
     * Instant.now() here, so all objects created in the same use case can share
     * one consistent time.
     */
    public static User register(String email, String passwordHash, Instant now) {
        return new User(UUID.randomUUID(), email, passwordHash, AccountStatus.ACTIVE, now, now);
    }

    public boolean canAuthenticate() {
        return status == AccountStatus.ACTIVE;
    }

    public void lock(Instant now) {
        this.status = AccountStatus.LOCKED;
        this.updatedAt = Objects.requireNonNull(now, "now must not be null");
    }

    public void disable(Instant now) {
        this.status = AccountStatus.DISABLED;
        this.updatedAt = Objects.requireNonNull(now, "now must not be null");
    }
}
